- name: insatlling and setting npm source
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: settup application
  ansible.builtin.import_role:
    name: common
    tasks_from: appsetup

- name: loading schema
  ansible.builtin.import_role:
    name: common
    tasks_from: load-mongodb-schema

- name: restarting service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup

